i=input('Digite algo: ')
print ('Só tem espaços? {}'.format (i.isspace()))
print ('É alfabetico ? {}'.format (i.isalpha()))
print ('É numerico ? {}'.format (i.isnumeric()))
print ('É alfanumerico ? {}'.format (i.isalnum()))
print ('Apenas letras maiusculas? {}'.format (i.isupper()))
print ('Apenas letras minusculas ? {}'.format (i.islower()))
print ('Esta capitalizada ? {}'.format (i.istitle()))
print ('Qual é o tipo primitivo ? {}'.format (type(i)))
